version: '3'

services:
  asr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-asr
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 